### PR TITLE
Fix invalid command in multiple artifacts test

### PR DESCRIPTION
**Pull request by jul-sh**
Should (hopefully!) fix https://github.com/slsa-framework/example-package/actions/runs/8562087181/job/23464658395#step:7:87

introduced in https://github.com/slsa-framework/example-package/pull/346

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]

**Comment by laurentsimon** [comment]
run in https://github.com/slsa-framework/example-package/actions/runs/8562302901

**Comment by laurentsimon** [comment]
sorry, here https://github.com/slsa-framework/example-package/actions/runs/8562304993

**Comment by jul-sh** [comment]
Okay, the good news is, it passed. The bad news is, the resulting attestation features only one, not two subjects 

```
{"_type":"https://in-toto.io/Statement/v0.1","subject":[{"name":"one.multi","digest":{"sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}}],"predicateType":"https://slsa.dev/provenance/v1","predicate":{"buildDefinition":{"buildType":"https://slsa.dev/container-based-build/v0.1?draft","externalParameters":{"source":{"uri":"git+https://github.com/slsa-framework/example-package@refs/heads/main","digest":{"sha1":"34f182a1b4878092b39231a95b4296dba6787c4c"}},"builderImage":{"uri":"bash@sha256:9e2ba52487d945504d250de186cb4fe2e3ba023ed2921dd6ac8b97ed43e76af9","digest":{"sha256":"9e2ba52487d945504d250de186cb4fe2e3ba023ed2921dd6ac8b97ed43e76af9"}},"configPath":".github/configs-docker/multi-config.toml","buildConfig":{"ArtifactPath":"*.multi","Command":["bash","-c","touch one.multi && mkdir nested-multi && touch nested-multi/two.multi"]}},"resolvedDependencies":[{"uri":"git+https://github.com/slsa-framework/example-package@refs/heads/main","digest":{"sha1":"34f182a1b4878092b39231a95b4296dba6787c4c"}},{"uri":"git+https://github.com/slsa-framework/slsa-github-generator@refs/heads/main","digest":{"sha256":"e747f3b4f745de67e392b7f015f189fa3a6ef9119a6872671229770c2d63a4c5"}}],"internalParameters":{"GITHUB_ACTOR_ID":"49289","GITHUB_EVENT_NAME":"push","GITHUB_REF":"refs/heads/main","GITHUB_REF_TYPE":"branch","GITHUB_REPOSITORY":"slsa-framework/example-package","GITHUB_REPOSITORY_ID":"486325809","GITHUB_REPOSITORY_OWNER_ID":"80431187","GITHUB_RUN_ATTEMPT":"1","GITHUB_RUN_ID":8562304993,"GITHUB_RUN_NUMBER":6,"GITHUB_SHA":"34f182a1b4878092b39231a95b4296dba6787c4c","GITHUB_TRIGGERING_ACTOR_ID":"49289","GITHUB_WORKFLOW":".github/workflows/e2e.container-based.push.main.multi.slsa3.yml","GITHUB_WORKFLOW_REF":"slsa-framework/example-package/.github/workflows/e2e.container-based.push.main.multi.slsa3.yml@refs/heads/main","GITHUB_WORKFLOW_SHA":"34f182a1b4878092b39231a95b4296dba6787c4c","GITHUB_BASE_REF":"","GITHUB_EVENT_PAYLOAD":{"after":"34f182a1b4878092b39231a95b4296dba6787c4c","base_ref":null,"before":"4cd170a6ebdadb795814259ea74bedb75e675a9d","commits":[{"author":{"email":"github-actions@github.com","name":"github-actions","username":"invalid-email-address"},"committer":{"email":"github-actions@github.com","name":"github-actions","username":"invalid-email-address"},"distinct":true,"id":"34f182a1b4878092b39231a95b4296dba6787c4c","message":".github/workflows/e2e.container-based.push.main.multi.slsa3.yml","timestamp":"2024-04-05T07:50:44+09:00","tree_id":"fb135b173824faf60f7841891fd88aff58ccd1f9","url":"https://github.com/slsa-framework/example-package/commit/34f182a1b4878092b39231a95b4296dba6787c4c"}],"compare":"https://github.com/slsa-framework/example-package/compare/4cd170a6ebda...34f182a1b487","created":false,"deleted":false,"enterprise":{"avatar_url":"https://avatars.githubusercontent.com/b/102459?v=4","created_at":"2023-12-08T05:54:26Z","description":"Open Source Security Foundation (OpenSSF)","html_url":"https://github.com/enterprises/openssf","id":102459,"name":"Open Source Security Foundation","node_id":"E_kgDOAAGQOw","slug":"openssf","updated_at":"2024-01-06T00:47:02Z","website_url":"https://openssf.org/"},"forced":false,"head_commit":{"author":{"email":"github-actions@github.com","name":"github-actions","username":"invalid-email-address"},"committer":{"email":"github-actions@github.com","name":"github-actions","username":"invalid-email-address"},"distinct":true,"id":"34f182a1b4878092b39231a95b4296dba6787c4c","message":".github/workflows/e2e.container-based.push.main.multi.slsa3.yml","timestamp":"2024-04-05T07:50:44+09:00","tree_id":"fb135b173824faf60f7841891fd88aff58ccd1f9","url":"https://github.com/slsa-framework/example-package/commit/34f182a1b4878092b39231a95b4296dba6787c4c"},"organization":{"avatar_url":"https://avatars.githubusercontent.com/u/80431187?v=4","description":"Supply-chain Levels for Software Artifacts","events_url":"https://api.github.com/orgs/slsa-framework/events","hooks_url":"https://api.github.com/orgs/slsa-framework/hooks","id":80431187,"issues_url":"https://api.github.com/orgs/slsa-framework/issues","login":"slsa-framework","members_url":"https://api.github.com/orgs/slsa-framework/members{/member}","node_id":"MDEyOk9yZ2FuaXphdGlvbjgwNDMxMTg3","public_members_url":"https://api.github.com/orgs/slsa-framework/public_members{/member}","repos_url":"https://api.github.com/orgs/slsa-framework/repos","url":"https://api.github.com/orgs/slsa-framework"},"pusher":{"email":"ianlewis@google.com","name":"ianlewis"},"ref":"refs/heads/main","repository":{"allow_forking":true,"archive_url":"https://api.github.com/repos/slsa-framework/example-package/{archive_format}{/ref}","archived":false,"assignees_url":"https://api.github.com/repos/slsa-framework/example-package/assignees{/user}","blobs_url":"https://api.github.com/repos/slsa-framework/example-package/git/blobs{/sha}","branches_url":"https://api.github.com/repos/slsa-framework/example-package/branches{/branch}","clone_url":"https://github.com/slsa-framework/example-package.git","collaborators_url":"https://api.github.com/repos/slsa-framework/example-package/collaborators{/collaborator}","comments_url":"https://api.github.com/repos/slsa-framework/example-package/comments{/number}","commits_url":"https://api.github.com/repos/slsa-framework/example-package/commits{/sha}","compare_url":"https://api.github.com/repos/slsa-framework/example-package/compare/{base}...{head}","contents_url":"https://api.github.com/repos/slsa-framework/example-package/contents/{+path}","contributors_url":"https://api.github.com/repos/slsa-framework/example-package/contributors","created_at":1651087843,"custom_properties":{},"default_branch":"main","deployments_url":"https://api.github.com/repos/slsa-framework/example-package/deployments","description":null,"disabled":false,"downloads_url":"https://api.github.com/repos/slsa-framework/example-package/downloads","events_url":"https://api.github.com/repos/slsa-framework/example-package/events","fork":false,"forks":23,"forks_count":23,"forks_url":"https://api.github.com/repos/slsa-framework/example-package/forks","full_name":"slsa-framework/example-package","git_commits_url":"https://api.github.com/repos/slsa-framework/example-package/git/commits{/sha}","git_refs_url":"https://api.github.com/repos/slsa-framework/example-package/git/refs{/sha}","git_tags_url":"https://api.github.com/repos/slsa-framework/example-package/git/tags{/sha}","git_url":"git://github.com/slsa-framework/example-package.git","has_discussions":false,"has_downloads":true,"has_issues":true,"has_pages":false,"has_projects":true,"has_wiki":true,"homepage":null,"hooks_url":"https://api.github.com/repos/slsa-framework/example-package/hooks","html_url":"https://github.com/slsa-framework/example-package","id":486325809,"is_template":false,"issue_comment_url":"https://api.github.com/repos/slsa-framework/example-package/issues/comments{/number}","issue_events_url":"https://api.github.com/repos/slsa-framework/example-package/issues/events{/number}","issues_url":"https://api.github.com/repos/slsa-framework/example-package/issues{/number}","keys_url":"https://api.github.com/repos/slsa-framework/example-package/keys{/key_id}","labels_url":"https://api.github.com/repos/slsa-framework/example-package/labels{/name}","language":"TypeScript","languages_url":"https://api.github.com/repos/slsa-framework/example-package/languages","license":{"key":"apache-2.0","name":"Apache License 2.0","node_id":"MDc6TGljZW5zZTI=","spdx_id":"Apache-2.0","url":"https://api.github.com/licenses/apache-2.0"},"master_branch":"main","merges_url":"https://api.github.com/repos/slsa-framework/example-package/merges","milestones_url":"https://api.github.com/repos/slsa-framework/example-package/milestones{/number}","mirror_url":null,"name":"example-package","node_id":"R_kgDOHPy-MQ","notifications_url":"https://api.github.com/repos/slsa-framework/example-package/notifications{?since,all,participating}","open_issues":39,"open_issues_count":39,"organization":"slsa-framework","owner":{"avatar_url":"https://avatars.githubusercontent.com/u/80431187?v=4","email":null,"events_url":"https://api.github.com/users/slsa-framework/events{/privacy}","followers_url":"https://api.github.com/users/slsa-framework/followers","following_url":"https://api.github.com/users/slsa-framework/following{/other_user}","gists_url":"https://api.github.com/users/slsa-framework/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/slsa-framework","id":80431187,"login":"slsa-framework","name":"slsa-framework","node_id":"MDEyOk9yZ2FuaXphdGlvbjgwNDMxMTg3","organizations_url":"https://api.github.com/users/slsa-framework/orgs","received_events_url":"https://api.github.com/users/slsa-framework/received_events","repos_url":"https://api.github.com/users/slsa-framework/repos","site_admin":false,"starred_url":"https://api.github.com/users/slsa-framework/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/slsa-framework/subscriptions","type":"Organization","url":"https://api.github.com/users/slsa-framework"},"private":false,"pulls_url":"https://api.github.com/repos/slsa-framework/example-package/pulls{/number}","pushed_at":1712271044,"releases_url":"https://api.github.com/repos/slsa-framework/example-package/releases{/id}","size":10469,"ssh_url":"git@github.com:slsa-framework/example-package.git","stargazers":15,"stargazers_count":15,"stargazers_url":"https://api.github.com/repos/slsa-framework/example-package/stargazers","statuses_url":"https://api.github.com/repos/slsa-framework/example-package/statuses/{sha}","subscribers_url":"https://api.github.com/repos/slsa-framework/example-package/subscribers","subscription_url":"https://api.github.com/repos/slsa-framework/example-package/subscription","svn_url":"https://github.com/slsa-framework/example-package","tags_url":"https://api.github.com/repos/slsa-framework/example-package/tags","teams_url":"https://api.github.com/repos/slsa-framework/example-package/teams","topics":[],"trees_url":"https://api.github.com/repos/slsa-framework/example-package/git/trees{/sha}","updated_at":"2024-01-01T05:54:12Z","url":"https://github.com/slsa-framework/example-package","visibility":"public","watchers":15,"watchers_count":15,"web_commit_signoff_required":true},"sender":{"avatar_url":"https://avatars.githubusercontent.com/u/49289?v=4","events_url":"https://api.github.com/users/ianlewis/events{/privacy}","followers_url":"https://api.github.com/users/ianlewis/followers","following_url":"https://api.github.com/users/ianlewis/following{/other_user}","gists_url":"https://api.github.com/users/ianlewis/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/ianlewis","id":49289,"login":"ianlewis","node_id":"MDQ6VXNlcjQ5Mjg5","organizations_url":"https://api.github.com/users/ianlewis/orgs","received_events_url":"https://api.github.com/users/ianlewis/received_events","repos_url":"https://api.github.com/users/ianlewis/repos","site_admin":false,"starred_url":"https://api.github.com/users/ianlewis/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ianlewis/subscriptions","type":"User","url":"https://api.github.com/users/ianlewis"}}}},"runDetails":{"builder":{"id":"https://github.com/slsa-framework/slsa-github-generator/.github/workflows/builder_container-based_slsa3.yml@refs/heads/main"},"metadata":{"invocationId":"https://github.com/slsa-framework/example-package/actions/runs/8562304993/attempts/1"}}}}
```

**Comment by jul-sh** [comment]
I'll debug a bit further and will follow up.

**Comment by laurentsimon** [comment]
I see. We'll need to update the verification code to verify both subjects, probably some tweaks in https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e-verify.common.sh#L317

**Pull request merged**
